name: Deploy to FTP

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.0.0

      - name: Install FTP Sync Action
        run: npm install -g ftp-sync

      - name: Deploy to FTP
        run: ftp-sync -r ./_next-e "open -u ${{ secrets.FTP_USER }} -p ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; mirror -R ./_next bye"
